export interface Provincias {
  provincia?: string;
  cantones: { [key: string]: Cantone };
}

export interface Cantone {
  canton: string;
  parroquias: { [key: string]: string } | null;
}
// export interface Provincias {
//   id: number;
//   provincia: string;
//   cantones: [Cantones];
// }
// export interface Cantones {
//   id: number;
//   canton: string;
//   parroquias: [Parroquias];
// }
// export interface Parroquias {
//   id: number;
//   canton: string;
//   parroquias: [string];
// }
// // Generated by https://quicktype.io
